services:
  server:
    environment:
      CLIENT_DOMAIN: https://paper.example.com
      API_DOMAIN: https://paper.example.com
      S3_PUBLIC_BASE_URL: https://paper.example.com/s3/openpaper-local
      CLOUDFLARE_BUCKET_NAME: paper.example.com/s3/openpaper-local
      GOOGLE_REDIRECT_URI: https://paper.example.com/api/auth/google/callback
      SECURE_COOKIES: "true"
      SESSION_COOKIE_DOMAIN: paper.example.com

  jobs-api:
    environment:
      S3_PUBLIC_BASE_URL: https://paper.example.com/s3/openpaper-local
      CLOUDFLARE_BUCKET_NAME: paper.example.com/s3/openpaper-local

  jobs-worker:
    environment:
      S3_PUBLIC_BASE_URL: https://paper.example.com/s3/openpaper-local
      CLOUDFLARE_BUCKET_NAME: paper.example.com/s3/openpaper-local
