"""rm paper and audio overview

Revision ID: c003d8a34483
Revises: 67d973ab2abe
Create Date: 2025-09-28 20:03:21.463959+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c003d8a34483"
down_revision: Union[str, None] = "67d973ab2abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "audio_overview_jobs_paper_id_fkey", "audio_overview_jobs", type_="foreignkey"
    )
    op.drop_column("audio_overview_jobs", "paper_id")
    op.drop_constraint(
        "audio_overviews_paper_id_fkey", "audio_overviews", type_="foreignkey"
    )
    op.drop_column("audio_overviews", "paper_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_overviews",
        sa.Column("paper_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "audio_overviews_paper_id_fkey",
        "audio_overviews",
        "papers",
        ["paper_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "audio_overview_jobs",
        sa.Column("paper_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "audio_overview_jobs_paper_id_fkey",
        "audio_overview_jobs",
        "papers",
        ["paper_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
