"""allow cascade deletes project > projectrole

Revision ID: c6c2b11964b3
Revises: 43cfb5c5fc93
Create Date: 2025-09-12 19:00:47.788189+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6c2b11964b3"
down_revision: Union[str, None] = "43cfb5c5fc93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("onboarding", "completed_at")
    op.drop_constraint(
        "project_role_project_id_fkey", "project_role", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_role", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_role", type_="foreignkey")
    op.create_foreign_key(
        "project_role_project_id_fkey",
        "project_role",
        "project",
        ["project_id"],
        ["id"],
    )
    op.add_column(
        "onboarding",
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
