"""add more paper metadata

Revision ID: 5058a675625a
Revises: 8022c5f77b58
Create Date: 2025-12-04 22:57:45.985031+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5058a675625a"
down_revision: Union[str, None] = "8022c5f77b58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("journal", sa.String(), nullable=True))
    op.add_column("papers", sa.Column("publisher", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "publisher")
    op.drop_column("papers", "journal")
    # ### end Alembic commands ###
