"""add email auth fields

Revision ID: a61351df8b96
Revises: 6dd9fa69fa45
Create Date: 2025-10-15 23:19:41.583763+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a61351df8b96"
down_revision: Union[str, None] = "6dd9fa69fa45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add email authentication fields to users table

    # First add the boolean column as nullable
    op.add_column("users", sa.Column("is_email_verified", sa.Boolean(), nullable=True))

    op.add_column(
        "users", sa.Column("email_verification_token", sa.String(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verification_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )

    # Set default value for existing users (they are OAuth users, so email is verified for their auth method)
    op.execute(
        "UPDATE users SET is_email_verified = true WHERE is_email_verified IS NULL"
    )

    # Make is_email_verified non-nullable after setting defaults
    op.alter_column("users", "is_email_verified", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verification_expires_at")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "is_email_verified")
    # ### end Alembic commands ###
