"""add forkable papers

Revision ID: 8022c5f77b58
Revises: 8afed8ffae09
Create Date: 2025-11-12 19:58:44.671851+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8022c5f77b58"
down_revision: Union[str, None] = "8afed8ffae09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("parent_paper_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "papers_parent_paper_id_fkey",
        "papers",
        "papers",
        ["parent_paper_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("papers", "open_alex_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("open_alex_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("papers_parent_paper_id_fkey", "papers", type_="foreignkey")
    op.drop_column("papers", "parent_paper_id")
    # ### end Alembic commands ###
