"""add conversable_type to audio overviews

Revision ID: 67d973ab2abe
Revises: c6c2b11964b3
Create Date: 2025-09-28 19:53:24.679370+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67d973ab2abe"
down_revision: Union[str, None] = "c6c2b11964b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_overview_jobs", sa.Column("conversable_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "audio_overview_jobs", sa.Column("conversable_type", sa.String(), nullable=True)
    )
    op.alter_column(
        "audio_overview_jobs", "paper_id", existing_type=sa.UUID(), nullable=True
    )
    op.add_column(
        "audio_overviews", sa.Column("conversable_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "audio_overviews", sa.Column("conversable_type", sa.String(), nullable=True)
    )
    op.alter_column(
        "audio_overviews", "paper_id", existing_type=sa.UUID(), nullable=True
    )

    connection = op.get_bind()

    # Migrate audio_overviews data
    connection.execute(
        sa.text(
            """
            UPDATE audio_overviews
            SET conversable_id = paper_id,
                conversable_type = 'paper'
            WHERE paper_id IS NOT NULL
        """
        )
    )

    # Migrate audio_overview_jobs data
    connection.execute(
        sa.text(
            """
            UPDATE audio_overview_jobs
            SET conversable_id = paper_id,
                conversable_type = 'paper'
            WHERE paper_id IS NOT NULL
        """
        )
    )

    op.alter_column(
        "audio_overviews", "conversable_type", nullable=False, server_default="paper"
    )
    op.alter_column(
        "audio_overview_jobs",
        "conversable_type",
        nullable=False,
        server_default="paper",
    )

    op.alter_column("audio_overviews", "conversable_id", nullable=False)
    op.alter_column("audio_overview_jobs", "conversable_id", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
            UPDATE audio_overviews
            SET paper_id = conversable_id
            WHERE conversable_type = 'paper' AND conversable_id IS NOT NULL
        """
        )
    )

    connection.execute(
        sa.text(
            """
            UPDATE audio_overview_jobs
            SET paper_id = conversable_id
            WHERE conversable_type = 'paper' AND conversable_id IS NOT NULL
        """
        )
    )

    op.alter_column(
        "audio_overviews", "paper_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("audio_overviews", "conversable_type")
    op.drop_column("audio_overviews", "conversable_id")
    op.alter_column(
        "audio_overview_jobs", "paper_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("audio_overview_jobs", "conversable_type")
    op.drop_column("audio_overview_jobs", "conversable_id")
    # ### end Alembic commands ###
