"""paper store extracted metadata at

Revision ID: 580b29285cba
Revises: 5058a675625a
Create Date: 2025-12-06 00:17:14.353412+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "580b29285cba"
down_revision: Union[str, None] = "5058a675625a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("attempted_metadata_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "attempted_metadata_at")
    # ### end Alembic commands ###
