"""position in highlight

Revision ID: 9818b3bcc53e
Revises: 8698e90090c3
Create Date: 2025-12-27 05:43:51.125810+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9818b3bcc53e"
down_revision: Union[str, None] = "8698e90090c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "highlights",
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("highlights", "position")
    # ### end Alembic commands ###
