"""add native onboarding

Revision ID: 43cfb5c5fc93
Revises: 32921fd74f14
Create Date: 2025-09-08 21:15:29.837595+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43cfb5c5fc93"
down_revision: Union[str, None] = "32921fd74f14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("research_fields", sa.String(), nullable=True),
        sa.Column("research_fields_other", sa.String(), nullable=True),
        sa.Column("job_titles", sa.String(), nullable=True),
        sa.Column("job_titles_other", sa.String(), nullable=True),
        sa.Column("reading_frequency", sa.String(), nullable=True),
        sa.Column("referral_source", sa.String(), nullable=True),
        sa.Column("referral_source_other", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("onboarding")
    # ### end Alembic commands ###
