"""color in highlight

Revision ID: c88a9d09eb28
Revises: 9818b3bcc53e
Create Date: 2025-12-30 02:15:30.455041+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c88a9d09eb28"
down_revision: Union[str, None] = "9818b3bcc53e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("highlights", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("highlights", "color")
    # ### end Alembic commands ###
