"""highlight type

Revision ID: 3ea97371f5fc
Revises: 8a530de3b9e6
Create Date: 2025-07-13 21:44:27.265371+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ea97371f5fc"
down_revision: Union[str, None] = "8a530de3b9e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("highlights", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("highlights", "type")
    # ### end Alembic commands ###
