"""rm hypothesis dead code

Revision ID: 1d41a48faee8
Revises: c88a9d09eb28
Create Date: 2025-12-31 05:19:01.017476+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d41a48faee8"
down_revision: Union[str, None] = "c88a9d09eb28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hypothesis_step_papers")
    op.drop_table("hypothesis_research_results")
    op.drop_table("hypothesis_steps")
    op.drop_table("hypothesis_jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hypothesis_step_papers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("step_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("abstract", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("publication_year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pdf_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("doi", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cited_by_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "was_selected_for_scraping",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scraping_attempted", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "scraping_successful", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("scraping_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("raw_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contextual_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reference_idx", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "scraped_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "summarized_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["hypothesis_steps.id"],
            name="hypothesis_step_papers_step_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="hypothesis_step_papers_pkey"),
    )
    op.create_table(
        "hypothesis_jobs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("original_question", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "generated_hypothesis", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("total_steps", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("completed_steps", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="hypothesis_jobs_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="hypothesis_jobs_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "hypothesis_steps",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("motivation", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "search_terms",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("step_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("findings", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["hypothesis_jobs.id"],
            name="hypothesis_steps_job_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="hypothesis_steps_pkey"),
    )
    op.create_table(
        "hypothesis_research_results",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("motivation", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("methodology", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("findings", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "limitations",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "future_research",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["hypothesis_jobs.id"],
            name="hypothesis_research_results_job_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="hypothesis_research_results_pkey"),
        sa.UniqueConstraint("job_id", name="hypothesis_research_results_job_id_key"),
    )
    # ### end Alembic commands ###
