"""add is_blocked to user

Revision ID: 0ceda25c2234
Revises: b3c4d5e6f7a8
Create Date: 2026-04-15 17:33:54.428515+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ceda25c2234"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Previous migration missed created_at and updated_at columns for paper_passages, adding them now
    op.add_column(
        "paper_passages",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "paper_passages",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )

    # Add is_blocked column to users table
    op.add_column(
        "users",
        sa.Column(
            "is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_blocked")
    op.drop_column("paper_passages", "updated_at")
    op.drop_column("paper_passages", "created_at")
    # ### end Alembic commands ###
